CREATE TABLE TEST_AUDIT
(	ID NUMBER(38,0), 
	NAME VARCHAR2(100)
);

BEGIN
	PKG_AUDIT.CREATE_AUDIT_OBJECTS(vTABLE_NAME => 'TEST_AUDIT');
END;

INSERT INTO TEST_AUDIT (ID, NAME) VALUES(1, 'TEST');

UPDATE TEST_AUDIT SET NAME = 'TEST_2' WHERE ID = 1;

DELETE FROM TEST_AUDIT WHERE ID = 1;

SELECT * FROM AUD_TEST_AUDIT;