CREATE OR REPLACE PACKAGE BODY PKG_AUD
AS

PROCEDURE CLEAR_AUD_TABLES
AS
	vERROR CLOB;
BEGIN
	FOR c IN (SELECT	ID,
						RUN_SCRIPT
				FROM CLEAR_AUD
				WHERE IS_ACTIVE = 'Y')
	LOOP
		BEGIN
			EXECUTE IMMEDIATE c.RUN_SCRIPT;
			UPDATE CLEAR_AUD
				SET ERROR_LOG = NULL,
					LAST_RUN_SUCCESS = 1,
					LAST_RUN_SUCCESS_DATE = SYSDATE
				WHERE ID = c.ID;
		EXCEPTION WHEN OTHERS THEN 
			vERROR := SQLERRM;
			UPDATE DBADMINDATA.CLEAR_LOGS
				SET ERROR_LOG = vERROR,
					LAST_RUN_SUCCESS = 0
				WHERE ID = c.ID;
		END;
	END LOOP;

END CLEAR_AUD_TABLES;

END PKG_AUD;