CREATE OR REPLACE PACKAGE PKG_AUD
AS

vSCHEMA_DEFAULT	varchar2(100) DEFAULT SYS_CONTEXT ('USERENV', 'CURRENT_USER');

PROCEDURE CREATE_CLEAR_AUD(	P_vSCHEMA		IN VARCHAR2,
							P_vTABLE_NAME	IN VARCHAR2,
							P_vCOLUMN_NAME	IN VARCHAR2,
							P_nTIME_TYPE	IN NUMBER,
							P_nDAYS_CNT		IN NUMBER,
							P_nMONTH_CNT	IN NUMBER,
							P_vIS_ACTIVE	IN VARCHAR2);

PROCEDURE UPDATE_CLEAR_AUD(	P_nID			IN NUMBER,
							P_vSCHEMA		IN VARCHAR2,
							P_vTABLE_NAME	IN VARCHAR2,
							P_vCOLUMN_NAME	IN VARCHAR2,
							P_nTIME_TYPE	IN NUMBER,
							P_nDAYS_CNT		IN NUMBER,
							P_nMONTH_CNT	IN NUMBER,
							P_vIS_ACTIVE	IN VARCHAR2);

PROCEDURE DELETE_CLEAR_AUD(P_nID IN NUMBER);

PROCEDURE CLEAR_AUD_TABLES;

END PKG_AUD;