CREATE OR REPLACE VIEW V_AUDIT_TABLES_OBJECTS_LIST(ID,T_SCHEMA,SOURCE_TABLE,AUD_TABLE,AUD_SEQ,AUD_TRIGGER,TABLE_TRIGGER,TIME_TYPE,DAYS_CNT,MONTHS_CNT,IS_ACTIVE)
AS
SELECT a.ID,
		a.T_SCHEMA,
		a.SOURCE_TABLE,
		a.AUD_TABLE,
		a.AUD_SEQ, 
		a.AUD_TRIGGER, 
		a.TABLE_TRIGGER,
		c.TIME_TYPE,
		c.DAYS_CNT,
		c.MONTHS_CNT,
		c.IS_ACTIVE
	FROM AUDIT_TABLES_OBJECTS_LIST a
	LEFT JOIN AUDIT_CLEAR c
		ON a.T_SCHEMA = c.T_SCHEMA
			AND a.AUD_TABLE = c.TABLE_NAME;